import { buildChallengeActivationMessageDraft, buildDefaultActivationInputs, deriveChallengeActivationRecommendation } from './actions';
import type {
  Challenge,
  ExecutiveOutput,
  Initiative,
  InitiativeOverlap,
  PortfolioDecisionItem,
  StrategicFront,
} from './types';

export const DEFAULT_STRATEGIC_FRONTS: StrategicFront[] = [
  {
    id: 'front-ops',
    name: 'Excelencia operativa',
    strategicObjective: 'Reducir friccion critica en procesos internos con impacto visible en productividad.',
    whyNow: 'El costo de la friccion ya se ve en tiempos, retrabajo y carga de supervision. Conviene intervenir antes de que escale.',
    area: 'Operaciones',
    mainKpi: 'Tiempo de ciclo operativo',
    baseline: '12 dias',
    target: '6 dias',
    threshold: 'Reducir al menos 20%',
    horizon: 'Q3 2026',
    endDate: '2026-09-30',
    sponsor: 'Roberto Jimenez',
    sponsorEmail: 'roberto.jimenez@starteria.io',
    priority: 'Alta',
    status: 'active',
    createdAt: '2026-04-02',
    lastUpdatedAt: '2026-05-02',
    challengeCount: 2,
    initiativeCount: 3,
  },
  {
    id: 'front-growth',
    name: 'Crecimiento digital',
    strategicObjective: 'Abrir nuevas oportunidades de adopcion y conversion en canales digitales.',
    whyNow: 'El canal digital ya muestra oportunidad de mejora y dejarlo quieto implicaria perder conversion y aprendizaje comercial.',
    area: 'Comercial',
    mainKpi: 'Conversion digital',
    baseline: '2.1%',
    target: '3.8%',
    threshold: 'Aumentar 15 puntos porcentuales',
    horizon: 'Q4 2026',
    endDate: '2026-12-15',
    sponsor: 'Laura Perez',
    sponsorEmail: 'laura.perez@starteria.io',
    priority: 'Media',
    status: 'active',
    createdAt: '2026-04-03',
    lastUpdatedAt: '2026-05-01',
    challengeCount: 1,
    initiativeCount: 1,
  },
];

export const DEFAULT_CHALLENGES: Challenge[] = [
  {
    id: 'challenge-open',
    name: 'Reducir friccion en onboarding interno',
    strategicFrontId: 'front-ops',
    challengeType: 'correccion',
    whatWeWantToMove: 'Reducir tiempos muertos y retrabajo durante las primeras dos semanas de onboarding.',
    objective: 'Aterrizar una solucion accionable para reducir friccion critica en onboarding sin depender de una redefinicion amplia del proceso.',
    whyNow: 'El cuello de botella ya afecta productividad, experiencia del colaborador y tiempo de supervisores.',
    successCriteria: 'Bajar de 12 a 6 dias el tiempo de habilitacion completa.',
    challengeOwner: 'Lider de Talento',
    sponsorName: 'Roberto Jimenez',
    horizon: 'Q3 2026',
    area: 'Operaciones',
    currentMetricValue: '9 días',
    activationMode: 'convocatoria_abierta',
    status: 'recibiendo_iniciativas',
    createdAt: '2026-04-02',
    lastUpdatedAt: '2026-05-02',
    challengeOwnerStatus: 'confirmado',
    sponsorStatus: 'confirmado',
    openCallStatus: 'activa',
    selectedPeople: [],
    assignedSquad: [],
    initiativeCount: 3,
    coverageStatus: 'cobertura_parcial',
    visibleToParticipants: true,
    publicationNotes: 'Ya esta visible para participantes del programa.',
    lastPublishedAt: '2026-04-05',
    activationInputs: {
      ...buildDefaultActivationInputs('confirmado'),
      urgency: 'alta',
      timeAvailable: 'suficiente',
      estimatedEffort: 'medio',
      challengeClarity: 'alta',
      informationSensitivity: 'baja',
      internalCapacity: 'media',
      technicalNeed: 'baja',
      dependency: 'operaciones',
    },
    activationRecommendationNote: '',
    activationMessageDraft: '',
  },
  {
    id: 'challenge-invite',
    name: 'Mejorar adopcion de tableros comerciales',
    strategicFrontId: 'front-growth',
    challengeType: 'crecimiento',
    whatWeWantToMove: 'Aumentar uso recurrente del tablero comercial por parte de jefaturas regionales.',
    objective: 'Abrir una via accionable para aumentar adopcion y convertir mejor el uso del tablero en decisiones comerciales sostenidas.',
    whyNow: 'Hay decisiones semanales sin respaldo oportuno porque la adopcion sigue baja.',
    successCriteria: 'Subir uso semanal recurrente del 32% al 60%.',
    challengeOwner: 'Head Comercial',
    sponsorName: 'Laura Perez',
    horizon: 'Q4 2026',
    area: 'Comercial',
    currentMetricValue: '41%',
    activationMode: 'personas_seleccionadas',
    status: 'publicado',
    createdAt: '2026-04-04',
    lastUpdatedAt: '2026-05-01',
    challengeOwnerStatus: 'confirmado',
    sponsorStatus: 'notificado',
    openCallStatus: 'inactiva',
    selectedPeople: [
      { id: 'invite-1', value: 'participante@starteria.io', status: 'notificado' },
      { id: 'invite-2', value: 'sofia@empresa.com', status: 'confirmado' },
    ],
    assignedSquad: [],
    initiativeCount: 1,
    coverageStatus: 'sin_cobertura',
    visibleToParticipants: true,
    publicationNotes: 'Visible solo para las personas invitadas.',
    lastPublishedAt: '2026-04-07',
    activationInputs: {
      ...buildDefaultActivationInputs('notificado'),
      urgency: 'media',
      timeAvailable: 'acotado',
      estimatedEffort: 'medio',
      challengeClarity: 'media',
      informationSensitivity: 'alta',
      internalCapacity: 'media',
      technicalNeed: 'baja',
      dependency: 'comercial',
    },
    activationRecommendationNote: '',
    activationMessageDraft: '',
  },
  {
    id: 'challenge-squad',
    name: 'Eliminar reprocesos en cierres de atencion',
    strategicFrontId: 'front-ops',
    challengeType: 'correccion',
    whatWeWantToMove: 'Reducir errores y reprocesos en el cierre operativo semanal.',
    objective: 'Corregir un punto de falla operativo que ya tiene costo visible y necesita una ruta concreta de activacion.',
    whyNow: 'El costo del retrabajo crecio y el squad ya esta definido, pero aun no se publica hacia participantes.',
    successCriteria: 'Reducir retrabajo semanal en 30%.',
    challengeOwner: 'Gerencia de Servicio',
    sponsorName: 'Roberto Jimenez',
    horizon: 'Q3 2026',
    area: 'Operaciones',
    currentMetricValue: 'Sin medición visible',
    activationMode: 'squad_asignado',
    status: 'activo_interno',
    createdAt: '2026-04-08',
    lastUpdatedAt: '2026-05-03',
    challengeOwnerStatus: 'confirmado',
    sponsorStatus: 'definido',
    openCallStatus: 'inactiva',
    selectedPeople: [],
    assignedSquad: [
      { id: 'squad-1', value: 'Ana Rodriguez', role: 'lider' },
      { id: 'squad-2', value: 'Miguel Torres', role: 'colaborador' },
    ],
    initiativeCount: 0,
    coverageStatus: 'sin_cobertura',
    visibleToParticipants: false,
    publicationNotes: 'Todavia no esta visible fuera del Portfolio Lead.',
    activationInputs: {
      ...buildDefaultActivationInputs('definido'),
      urgency: 'alta',
      timeAvailable: 'muy_poco',
      estimatedEffort: 'alto',
      challengeClarity: 'alta',
      informationSensitivity: 'media',
      internalCapacity: 'alta',
      technicalNeed: 'media',
      dependency: 'operaciones',
    },
    activationRecommendationNote: '',
    activationMessageDraft: '',
  },
];

DEFAULT_CHALLENGES.forEach(challenge => {
  const front = DEFAULT_STRATEGIC_FRONTS.find(item => item.id === challenge.strategicFrontId) ?? null;
  const recommendation = deriveChallengeActivationRecommendation(challenge, front);
  challenge.activationRecommendationNote = recommendation.justification;
  challenge.activationMessageDraft = buildChallengeActivationMessageDraft(challenge, recommendation, front);
});

export const DEFAULT_INITIATIVES: Initiative[] = [
  {
    id: 'initiative-a',
    name: 'Piloto de onboarding guiado',
    strategicFrontId: 'front-ops',
    challengeId: 'challenge-open',
    teamOwner: 'Ana Rodriguez',
    currentStep: 'Step 4',
    status: 'lista_para_decision',
    mentor: 'Carlos Mendez',
    sponsorTouchpoint: 'Revision final agendada con sponsor',
    mainAlert: 'Necesita decision de salida y capacidad para escalar.',
    nextActionRecommended: 'Llevarla a decisiones con foco en segunda fase o piloto ampliado.',
    attackedArea: 'Friccion inicial de accesos y habilitacion',
    hypothesisCovered: 'Si se guia al colaborador y al aprobador desde el dia 1, baja el tiempo de espera.',
    mainMetric: 'Tiempo de habilitacion completa',
    contributionType: 'resolver_parcialmente',
    estimatedContribution: 'alto',
    lastActivity: 'Hoy, revision de evidencia de Step 4',
    signalSummary: 'Redujo 34% del tiempo en el piloto y mejoro claridad para managers.',
    mainBlocker: 'Falta definir capacidad de implementacion y alcance siguiente.',
    teamLabel: 'Squad onboarding',
    requiresSponsor: true,
    readyForDecision: true,
    blockedDays: 0,
    requiresExternalCapability: false,
    partialSignal: false,
    resolvedCorePart: true,
    teamMembers: ['Ana Rodriguez', 'Miguel Torres', 'Roberto Jimenez'],
    executiveSummary: 'El equipo completo el piloto de onboarding guiado y ya demostro una reduccion visible del tiempo de habilitacion.',
    experimentSummary: 'Se corrio un piloto con 12 ingresos nuevos. La secuencia guiada redujo esperas, aclaro tareas criticas y bajo retrabajo del lider.',
    deliverables: [
      { id: 'deliv-a1', title: 'Resumen ejecutivo del piloto', type: 'Resumen', note: 'Sintesis de resultados, aprendizajes y siguiente paso sugerido.' },
      { id: 'deliv-a2', title: 'Deck de evidencia de Step 4', type: 'Deck', note: 'Slides con metricas, hallazgos y lectura de implementacion.' },
      { id: 'deliv-a3', title: 'Mapa de flujo ajustado', type: 'PDF', note: 'Documento comparativo antes vs despues del piloto.' },
    ],
    aiCommentSummary: 'La IA considera que la evidencia ya sostiene una salida clara y que el riesgo principal es de capacidad de implementacion, no de valor.',
    mentorCommentSummary: 'El mentor valida que el equipo resolvio la friccion principal y recomienda pasar a una fase controlada de escalamiento.',
    decisionRecommendationReason: 'Llega a decisiones porque esta en Step 4, tiene evidencia suficiente y ya resolvio una parte clara del reto.',
    stepsTimeline: [
      { step: 'Step 0', state: 'completado', note: 'Quedo claro el cuello de botella y el alcance inicial del reto.' },
      { step: 'Step 1', state: 'completado', note: 'El equipo confirmo la friccion principal con evidencia de usuarios y proceso.' },
      { step: 'Step 2', state: 'completado', note: 'Se priorizo una solucion guiada con criterio de impacto y viabilidad.' },
      { step: 'Step 3', state: 'completado', note: 'El piloto corrio con usuarios reales y registro mejora de tiempo.' },
      { step: 'Step 4', state: 'completado', note: 'La evidencia ya esta empaquetada para decidir escalamiento.' },
    ],
  },
  {
    id: 'initiative-b',
    name: 'Checklist inteligente para lideres',
    strategicFrontId: 'front-ops',
    challengeId: 'challenge-open',
    teamOwner: 'Miguel Torres',
    currentStep: 'Step 2',
    status: 'bloqueada',
    mentor: '',
    sponsorTouchpoint: '',
    mainAlert: 'Sigue bloqueada por falta de soporte tecnico para integrarse al sistema actual.',
    nextActionRecommended: 'Revisar si conviene transferir a TI o abrir camino de innovacion abierta.',
    attackedArea: 'Seguimiento de tareas del lider',
    hypothesisCovered: 'Un checklist dinamico reduce olvidos y retrabajo.',
    mainMetric: 'Cumplimiento de tareas de onboarding',
    contributionType: 'validar',
    estimatedContribution: 'medio',
    lastActivity: 'Hace 18 dias, ultimo ajuste de tarjeta de experimento',
    signalSummary: 'Hay interes, pero no se pudo validar por falta de integracion disponible.',
    mainBlocker: 'No hay capacidad tecnica interna asignada.',
    teamLabel: 'Equipo de operaciones',
    requiresSponsor: false,
    readyForDecision: false,
    blockedDays: 18,
    requiresExternalCapability: true,
    partialSignal: true,
    resolvedCorePart: false,
    teamMembers: ['Miguel Torres', 'Claudia Ruiz'],
    executiveSummary: 'La propuesta tiene sentido operativo, pero el equipo no pudo ejecutarla por falta de capacidad tecnica para integracion.',
    experimentSummary: 'Se definio una prueba de checklist inteligente, pero no pudo pasar de prototipo porque depende de integracion con sistemas internos.',
    deliverables: [
      { id: 'deliv-b1', title: 'Tarjeta de experimento bloqueada', type: 'Resumen', note: 'Resume hipotesis, alcance y razon del bloqueo actual.' },
      { id: 'deliv-b2', title: 'Prototipo funcional de flujo', type: 'Link', note: 'Mock del checklist y del comportamiento esperado.' },
    ],
    aiCommentSummary: 'La IA detecta valor potencial, pero recomienda no seguir iterando sin resolver primero la dependencia tecnica.',
    mentorCommentSummary: 'El mentor sugiere decidir pronto si esto pasa a TI o se reformula desde una solucion menos dependiente.',
    decisionRecommendationReason: 'Entra a decisiones porque esta bloqueada hace mas de 14 dias y requiere un destrabe externo.',
    stepsTimeline: [
      { step: 'Step 0', state: 'completado', note: 'El equipo definio la friccion del lider y la necesidad de seguimiento.' },
      { step: 'Step 1', state: 'completado', note: 'La validacion inicial confirmo que el olvido de tareas genera retrabajo.' },
      { step: 'Step 2', state: 'bloqueado', note: 'La solucion requiere integracion y eso freno el experimento.' },
      { step: 'Step 3', state: 'pendiente', note: 'No se ejecuto piloto por falta de soporte tecnico.' },
      { step: 'Step 4', state: 'pendiente', note: 'Todavia no hay caso para cierre ejecutivo.' },
    ],
  },
  {
    id: 'initiative-c',
    name: 'Segmentacion por tipo de ingreso',
    strategicFrontId: 'front-ops',
    challengeId: 'challenge-open',
    teamOwner: 'Celula de Talento',
    currentStep: 'Step 1',
    status: 'esperando_revision',
    mentor: 'Mentor de descubrimiento',
    sponsorTouchpoint: 'Revision de enfoque la proxima semana',
    mainAlert: 'Aun falta validar si el problema cambia segun tipo de ingreso.',
    nextActionRecommended: 'Profundizar evidencia y decidir si se fusiona con la iniciativa principal.',
    attackedArea: 'Causa secundaria del reto',
    hypothesisCovered: 'No todos los ingresos sufren la misma friccion.',
    mainMetric: 'Tiempo por tipo de colaborador',
    contributionType: 'descubrir',
    estimatedContribution: 'bajo',
    lastActivity: 'Ayer, carga de entrevistas',
    signalSummary: 'Aparece una senal parcial, pero aun no cambia la ruta principal.',
    mainBlocker: 'Falta evidencia suficiente en perfiles criticos.',
    teamLabel: 'Celula de descubrimiento',
    requiresSponsor: false,
    readyForDecision: false,
    blockedDays: 0,
    requiresExternalCapability: false,
    partialSignal: true,
    resolvedCorePart: false,
    teamMembers: ['Celula de Talento', 'Mentor de descubrimiento'],
    executiveSummary: 'La iniciativa sigue abierta como exploracion complementaria y aun necesita evidencia para justificar si continua o se fusiona.',
    experimentSummary: 'El equipo viene recogiendo entrevistas y patrones por tipo de ingreso para validar si existe una segunda causa del problema.',
    deliverables: [
      { id: 'deliv-c1', title: 'Resumen de entrevistas', type: 'PDF', note: 'Hallazgos preliminares por perfil de colaborador.' },
      { id: 'deliv-c2', title: 'Matriz de patrones', type: 'Resumen', note: 'Sintesis de diferencias entre tipos de ingreso.' },
    ],
    aiCommentSummary: 'La IA ve una senal interesante, pero aun no suficiente para abrir una decision de salida.',
    mentorCommentSummary: 'El mentor recomienda terminar de contrastar perfiles criticos antes de fusionar o cerrar.',
    decisionRecommendationReason: 'Se mantiene en seguimiento porque aun esta esperando revision y no tiene evidencia suficiente para una decision ejecutiva.',
    stepsTimeline: [
      { step: 'Step 0', state: 'completado', note: 'Se definio la hipotesis sobre una causa secundaria del reto.' },
      { step: 'Step 1', state: 'en_progreso', note: 'Sigue abierta la validacion con perfiles criticos.' },
      { step: 'Step 2', state: 'pendiente', note: 'Todavia no conviene bajar a solucion.' },
      { step: 'Step 3', state: 'pendiente', note: 'No aplica hasta cerrar la validacion.' },
      { step: 'Step 4', state: 'pendiente', note: 'Sin evidencia suficiente para decision.' },
    ],
  },
  {
    id: 'initiative-d',
    name: 'Ruta de adopcion por region',
    strategicFrontId: 'front-growth',
    challengeId: 'challenge-invite',
    teamOwner: 'Sofia Vargas',
    currentStep: 'Step 3',
    status: 'en_step_3',
    mentor: 'Mentor comercial',
    sponsorTouchpoint: 'Seguimiento quincenal con Head Comercial',
    mainAlert: 'La prueba va bien, pero aun no queda claro si escala a todas las regiones.',
    nextActionRecommended: 'Cerrar piloto y preparar evidencia para evaluar segunda fase.',
    attackedArea: 'Uso recurrente de tableros por jefaturas',
    hypothesisCovered: 'Una ruta simple por region mejora adopcion en managers.',
    mainMetric: 'Uso semanal recurrente',
    contributionType: 'resolver_parcialmente',
    estimatedContribution: 'medio',
    lastActivity: 'Hoy, nueva medicion de adopcion',
    signalSummary: 'Subio 14 puntos en dos regiones piloto.',
    mainBlocker: 'Falta definir soporte para regiones restantes.',
    teamLabel: 'Equipo comercial regional',
    requiresSponsor: true,
    readyForDecision: false,
    blockedDays: 0,
    requiresExternalCapability: false,
    partialSignal: true,
    resolvedCorePart: true,
    teamMembers: ['Sofia Vargas', 'Equipo comercial regional'],
    executiveSummary: 'La iniciativa muestra una mejora parcial en adopcion y necesita cerrar el piloto para decidir si entra a segunda fase.',
    experimentSummary: 'Se testeo una ruta de adopcion por region en dos equipos. La mejora es visible, pero la cobertura aun es parcial.',
    deliverables: [
      { id: 'deliv-d1', title: 'Tablero de adopcion piloto', type: 'Link', note: 'Metricas de uso por region durante la prueba.' },
      { id: 'deliv-d2', title: 'Resumen de aprendizajes', type: 'Resumen', note: 'Lo que funciono, lo que no y condiciones para escalar.' },
    ],
    aiCommentSummary: 'La IA recomienda cerrar mejor la evidencia comparativa antes de llevarla a una decision de escalamiento.',
    mentorCommentSummary: 'El mentor ve avance real y sugiere ordenar mejor los entregables para siguiente comite.',
    decisionRecommendationReason: 'Se mantiene en seguimiento porque aun esta en progreso, aunque ya tiene senales que podrian llevarla a decision pronto.',
    stepsTimeline: [
      { step: 'Step 0', state: 'completado', note: 'El problema de adopcion fue definido con claridad por region.' },
      { step: 'Step 1', state: 'completado', note: 'Se confirmo la friccion principal en managers regionales.' },
      { step: 'Step 2', state: 'completado', note: 'Se eligio una ruta de adopcion simple y medible.' },
      { step: 'Step 3', state: 'en_progreso', note: 'El piloto sigue abierto en dos regiones y falta cerrar lectura final.' },
      { step: 'Step 4', state: 'pendiente', note: 'Aun no esta lista la narrativa ejecutiva final.' },
    ],
  },
];

export const DEFAULT_INITIATIVE_OVERLAPS: InitiativeOverlap[] = [
  {
    id: 'overlap-1',
    challengeId: 'challenge-open',
    initiativeAId: 'initiative-a',
    initiativeBId: 'initiative-c',
    level: 'medio',
    rationale: 'Ambas iniciativas tocan el mismo flujo de onboarding, pero desde angulos distintos.',
    recommendation: 'seguir',
  },
];

export const DEFAULT_PORTFOLIO_DECISIONS: PortfolioDecisionItem[] = [
  {
    id: 'decision-1',
    challengeId: 'challenge-open',
    initiativeId: 'initiative-a',
    recommendation: 'escalar_piloto',
    summary: 'La iniciativa resolvio una parte clara del reto y ya tiene evidencia visible para decidir siguiente fase.',
    successReading: 'El piloto mostro mejora concreta en tiempo y claridad operativa.',
    reviewReason: 'Falta decidir si escala como piloto ampliado o entra a segunda fase formal.',
  },
  {
    id: 'decision-2',
    challengeId: 'challenge-open',
    initiativeId: 'initiative-b',
    recommendation: 'transferir_a_ti',
    summary: 'La iniciativa tiene senal parcial, pero depende de una capacidad tecnica que hoy no esta disponible.',
    successReading: 'La necesidad existe, pero la prueba no pudo ejecutarse con el stack actual.',
    reviewReason: 'La iniciativa lleva mas de dos semanas bloqueada por integracion.',
  },
];

export const DEFAULT_EXECUTIVE_OUTPUTS: ExecutiveOutput[] = [
  {
    id: 'exec-initiative-a',
    challengeId: 'challenge-open',
    initiativeId: 'initiative-a',
    recommendation: 'escalar_piloto',
    status: 'listo_para_compartir',
    whyNow: 'El cuello de botella ya afecta productividad y la iniciativa ya demostro una mejora real en piloto.',
    kpiToMove: 'Tiempo de habilitacion completa',
    approachSummary: 'El equipo piloteo una ruta guiada de onboarding con responsables y tareas visibles desde el dia 1.',
    scopeSummary: 'Piloto controlado con 12 ingresos nuevos y seguimiento comparativo contra el flujo anterior.',
    evidenceSummary: 'La iniciativa redujo 34% del tiempo de habilitacion y mejoro claridad para managers.',
    keyDeliverableSummary: 'Deck de evidencia de Step 4 con metricas, aprendizajes y condiciones de escalamiento.',
    cautionSummary: 'La evidencia es fuerte para una siguiente fase controlada, pero aun falta definir capacidad de implementacion.',
    recommendationWhy: 'Se recomienda escalar piloto porque ya resolvio una parte clara del reto y el riesgo principal ya no es de valor sino de despliegue.',
    secondaryOptions: 'Como segunda opcion podria pasar a segunda fase sin escalar aun, pero eso retrasaria una oportunidad ya validada.',
    managementNeeds: ['Prioridad para implementacion', 'Capacidad operativa y tecnica', 'Sponsor para destrabar adopcion'],
    nextStepSummary: 'Escalar el piloto a un grupo mas amplio con seguimiento ejecutivo quincenal.',
    nextStepOwner: 'Ana Rodriguez con apoyo de Operaciones',
    nextStepHorizon: '6 semanas',
    nextStepExpectedResult: 'Validar sostenibilidad del impacto y preparar decision de implementacion ampliada.',
    timeline: [
      { label: 'Decision interna tomada', note: 'Portfolio Lead recomienda escalar piloto.' },
      { label: 'Borrador ejecutivo preparado', note: 'La narrativa ya esta lista para sponsor o gerencia.' },
      { label: 'Siguiente hito', note: 'Compartir con gerencia y pedir prioridad para despliegue controlado.' },
    ],
  },
  {
    id: 'exec-initiative-b',
    challengeId: 'challenge-open',
    initiativeId: 'initiative-b',
    recommendation: 'transferir_a_ti',
    status: 'borrador_ejecutivo',
    whyNow: 'El problema sigue vigente, pero la iniciativa no puede avanzar sin capacidad tecnica.',
    kpiToMove: 'Cumplimiento de tareas de onboarding',
    approachSummary: 'El equipo definio un checklist inteligente y un prototipo operativo para reducir olvidos y retrabajo.',
    scopeSummary: 'Trabajo conceptual y prototipo funcional sin despliegue por dependencia de integracion.',
    evidenceSummary: 'La necesidad esta validada, pero no hubo prueba completa porque falta soporte tecnico.',
    keyDeliverableSummary: 'Tarjeta de experimento bloqueada y mock funcional del flujo esperado.',
    cautionSummary: 'No conviene seguir iterando desde negocio sin destrabar antes la dependencia con TI.',
    recommendationWhy: 'Se recomienda transferir a TI porque el siguiente cuello de botella ya no es de diseno del experimento, sino de capacidad tecnica.',
    secondaryOptions: 'Otra opcion seria reformular hacia una solucion manual de menor alcance, pero perderia parte del valor buscado.',
    managementNeeds: ['Priorizacion tecnica', 'Asignacion de responsable en TI', 'Decision sobre alcance minimo viable'],
    nextStepSummary: 'Definir si TI toma el caso y con que prioridad entra al roadmap.',
    nextStepOwner: 'Portfolio Lead con responsable de TI',
    nextStepHorizon: '2 semanas',
    nextStepExpectedResult: 'Confirmar viabilidad tecnica o bajar el caso a una alternativa de menor dependencia.',
    timeline: [
      { label: 'Decision interna tomada', note: 'Portfolio Lead sugiere transferencia a TI.' },
      { label: 'Borrador ejecutivo en construccion', note: 'Aun falta dejar lista la narrativa para gerencia.' },
      { label: 'Siguiente hito', note: 'Compartir con sponsor o gerencia para destrabar capacidad.' },
    ],
  },
];
