import React from 'react';
import { useParams } from 'react-router';
import { useStrategicFramingWorkspace } from './useStrategicFramingWorkspace';
import type { StrategicFramingDraft, SubjectLevel } from './types';

const subjectLabels: Record<SubjectLevel, string> = { front_like: 'Frente estratégico posible', challenge_like: 'Reto o problema específico', initiative_like: 'Iniciativa o intervención', unresolved: 'Aún por definir' };
const parentLabels = { known: 'Contexto estratégico identificado', provisional: 'Relación estratégica por validar', unresolved: 'Contexto estratégico aún no resuelto' };
const sourceLabels: Record<string, string> = { public_entry: 'Entrada pública', enterprise_direct: 'Entrada corporativa', existing_portfolio: 'Portafolio existente' };

export function StrategicFramingWorkspacePage() {
  const { stateId = '' } = useParams();
  const workspace = useStrategicFramingWorkspace(stateId);
  if (workspace.status === 'loading') return <StateMessage text="Cargando el framing provisional…" />;
  if (workspace.status === 'error' && !workspace.serverState) return <StateMessage text={workspace.error?.code === 'SF_PROVISIONAL_STATE_NOT_FOUND' ? 'No encontramos este framing provisional.' : workspace.error?.code === 'SF_PROVISIONAL_STATE_FORBIDDEN' ? 'No tienes acceso a este framing.' : 'No pudimos cargar este framing.'} action={workspace.reload} />;
  if (!workspace.serverState || !workspace.draft) return null;
  const { serverState: state, draft } = workspace;
  const field = (key: keyof StrategicFramingDraft) => (value: string) => workspace.update(key, value || null);
  return <main className="mx-auto max-w-7xl space-y-6 p-6 md:p-10">
    <div className="text-sm text-slate-500"><a href="/portfolio/inicio" className="hover:text-slate-900">Portfolio Lead</a> <span className="mx-2">/</span> Strategic Framing</div>
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-700">Strategic Framing</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{draft.intendedMovement || 'Define qué quieres mover'}</h1><p className="mt-2 max-w-2xl text-slate-600">Estado provisional. Revisa y ajusta cómo estamos entendiendo este contexto antes de convertirlo en estructura estratégica formal.</p></div>
      <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Provisional</strong><div className="mt-1 text-xs">Versión {state.version} · {sourceLabels[state.sourceMode] ?? 'Origen no especificado'}</div></div>
    </header>
    {workspace.conflict && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">Este framing fue actualizado en otra sesión. Recarga la versión más reciente antes de guardar tus cambios.<button className="rounded-xl bg-white px-3 py-2 font-semibold" onClick={workspace.reload}>Recargar versión</button></div>}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
      <section className="space-y-6">
        <Card title="Qué quieres mover"><TextArea label="Movimiento intencionado" value={draft.intendedMovement} onChange={field('intendedMovement')} /><TextArea label="Por qué importa" value={draft.whyItMatters} onChange={field('whyItMatters')} /></Card>
        <Card title="Cómo lo estamos interpretando"><label className="block text-sm font-semibold text-slate-700">Clasificación actual<select className="mt-2 w-full rounded-xl border border-slate-200 p-3" value={draft.subjectLevel} onChange={e => workspace.update('subjectLevel', e.target.value as SubjectLevel)}>{Object.entries(subjectLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><strong>Interpretación inicial de Starteria</strong><p className="mt-2">Confianza: {state.scopeAssessment.confidence}</p>{state.scopeAssessment.rationale.map(item => <p key={item} className="mt-1">{item}</p>)}</div></Card>
        <Card title="Cómo sabremos que se mueve"><div className="grid gap-4 md:grid-cols-2"><Select label="Estado de la señal" value={draft.movementSignalStatus ?? ''} options={['confirmed', 'proxy', 'suggested', 'unknown', 'conflicting']} onChange={value => workspace.update('movementSignalStatus', (value || null) as StrategicFramingDraft['movementSignalStatus'])} /><TextInput label="Señal o valor proxy" value={draft.movementSignalValue} onChange={field('movementSignalValue')} /></div><TextArea label="Horizonte" value={draft.horizonContext} onChange={field('horizonContext')} /><TextArea label="Decisión que habilita" value={draft.decisionToEnable} onChange={field('decisionToEnable')} /></Card>
        <Card title="Relación estratégica"><Select label="Estado del contexto" value={draft.parentStatus} options={Object.keys(parentLabels)} optionLabels={parentLabels} onChange={value => workspace.update('parentStatus', value as StrategicFramingDraft['parentStatus'])} /><TextInput label="Descripción humana del contexto" value={draft.parentLabel} onChange={field('parentLabel')} /></Card>
      </section>
      <aside className="space-y-6"><Card title="Qué falta para avanzar"><p className="text-xs uppercase tracking-wide text-slate-500">Evaluación actual · {state.sufficiency.status}</p><Gap title="Bloqueos" items={state.sufficiency.blockers} /><Gap title="Brechas suaves" items={state.sufficiency.softGaps} /><Gap title="Contexto opcional" items={state.sufficiency.optionalContext} /></Card><Card title="Contexto"><p className="text-sm text-slate-600">Última actualización</p><p className="mt-1 text-sm font-semibold text-slate-900">{new Date(state.updatedAt).toLocaleString('es-ES')}</p><p className="mt-4 text-sm text-slate-600">La procedencia y la evaluación son de solo lectura en esta versión.</p></Card></aside>
    </div>
    <footer className="flex justify-end gap-3 border-t border-slate-200 pt-5"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700" onClick={workspace.cancel} disabled={!workspace.dirty}>Cancelar cambios</button><button className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40" onClick={workspace.save} disabled={!workspace.dirty || workspace.status === 'saving'}>{workspace.status === 'saving' ? 'Guardando…' : 'Guardar cambios'}</button></footer>
  </main>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold text-slate-950">{title}</h2>{children}</section>; }
function TextInput({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string) => void }) { return <label className="mt-4 block text-sm font-semibold text-slate-700">{label}<input className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" value={value ?? ''} onChange={e => onChange(e.target.value)} /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string) => void }) { return <label className="mt-4 block text-sm font-semibold text-slate-700">{label}<textarea className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 p-3 font-normal" value={value ?? ''} onChange={e => onChange(e.target.value)} /></label>; }
function Select({ label, value, options, optionLabels, onChange }: { label: string; value: string; options: string[]; optionLabels?: Record<string, string>; onChange: (value: string) => void }) { return <label className="block text-sm font-semibold text-slate-700">{label}<select className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" value={value} onChange={e => onChange(e.target.value)}><option value="">Selecciona una opción</option>{options.map(option => <option key={option} value={option}>{optionLabels?.[option] ?? option}</option>)}</select></label>; }
function Gap({ title, items }: { title: string; items: string[] }) { return <div className="mt-4"><h3 className="text-sm font-semibold text-slate-800">{title}</h3>{items.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{items.map(item => <li key={item}>{item}</li>)}</ul> : <p className="mt-1 text-sm text-slate-500">Ninguno registrado.</p>}</div>; }
function StateMessage({ text, action }: { text: string; action?: () => void }) { return <main className="mx-auto max-w-3xl p-10"><div className="rounded-3xl border border-slate-200 bg-white p-8 text-center"><p className="text-slate-700">{text}</p>{action && <button className="mt-5 rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white" onClick={action}>Reintentar</button>}</div></main>; }
