apiVersion: v1
kind: Service
metadata:
  name: starteria-ai-service
  namespace: starteria
  labels:
    app: starteria-ai-service
spec:
  type: ClusterIP
  selector:
    app: starteria-ai-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
