import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { loadPortfolioEntryProviderConfig } from '../../backend/modules/portfolio-entry-runtime/model/provider-config';
import { HarnessFetchStructuredModelAdapter } from './harness-fetch-structured-model-adapter';
import { integrateDecisionReadinessProjection, type IntegratedProjection } from './decision-readiness-metadata-integration';
import { validateProjectedItem, type AuthoritativeReadinessMetadata, type RelationshipItem } from './authoritative-current-later-projection';
import { runDecisionReadinessFixture, type DecisionReadinessRun } from '../portfolio-entry-decision-readiness/decision-readiness-adapter';
import type { StructuredModelGenerateInput } from '../../backend/modules/portfolio-entry-runtime/model/structured-model-adapter';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const base = path.join(root, 'docs/portfolio-entry/testing');
const fixturePath = path.join(base, 'PORTFOLIO_ENTRY_CONVERSION_READINESS_FIXTURES_v0.1.json');
const promptPath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'decision-readiness-live-prompt.v0.1.md');
const runsPath = path.join(base, 'PORTFOLIO_ENTRY_FINAL_CANDIDATE_CONFIRMATION_RUNS_v0.1.json');
const reportPath = path.join(base, 'PORTFOLIO_ENTRY_FINAL_CANDIDATE_CONFIRMATION_REPORT_v0.1.md');

const outputSchema = z.object({
  selected_material_gap: z.string(), next_action: z.enum(['ASK', 'STOP', 'ROUTE', 'REQUIRE_ORGANIZATIONAL_INPUT']),
  deferred_gaps: z.array(z.string()), routing_target: z.string().nullable(), stop_rationale: z.string().nullable(),
  understood_need: z.string().nullable(), desired_outcome: z.string().nullable(), known_context: z.array(z.string()),
  current_open_items: z.array(z.object({ description: z.string(), why_it_matters: z.string(), who_can_help_resolve_it: z.string().nullable(), suggested_next_move: z.string(), relation: z.enum(['CURRENT_DECISION_BLOCKER', 'CURRENT_DECISION_CONDITION']) }).strict()),
  later_work_items: z.array(z.object({ description: z.string(), why_it_matters: z.string(), who_can_help_resolve_it: z.string().nullable(), suggested_next_move: z.string(), relation: z.enum(['LATER_WORK', 'OPTIONAL_ENRICHMENT']) }).strict()),
  visible_question: z.string().nullable(), suggested_next_moves: z.array(z.string()), visible_response: z.string().optional(),
}).strict();

const itemSchema = (relations: string[]) => ({ type: 'array', items: { type: 'object', additionalProperties: false, required: ['description', 'why_it_matters', 'who_can_help_resolve_it', 'suggested_next_move', 'relation'], properties: { description: { type: 'string' }, why_it_matters: { type: 'string' }, who_can_help_resolve_it: { anyOf: [{ type: 'string' }, { type: 'null' }] }, suggested_next_move: { type: 'string' }, relation: { type: 'string', enum: relations } } } });
const providerJsonSchema = { type: 'object', additionalProperties: false, required: ['selected_material_gap','next_action','deferred_gaps','routing_target','stop_rationale','understood_need','desired_outcome','known_context','current_open_items','later_work_items','visible_question','suggested_next_moves'], properties: { selected_material_gap: { type: 'string' }, next_action: { type: 'string', enum: ['ASK','STOP','ROUTE','REQUIRE_ORGANIZATIONAL_INPUT'] }, deferred_gaps: { type: 'array', items: { type: 'string' } }, routing_target: { anyOf: [{ type: 'string' }, { type: 'null' }] }, stop_rationale: { anyOf: [{ type: 'string' }, { type: 'null' }] }, understood_need: { anyOf: [{ type: 'string' }, { type: 'null' }] }, desired_outcome: { anyOf: [{ type: 'string' }, { type: 'null' }] }, known_context: { type: 'array', items: { type: 'string' } }, current_open_items: itemSchema(['CURRENT_DECISION_BLOCKER','CURRENT_DECISION_CONDITION']), later_work_items: itemSchema(['LATER_WORK','OPTIONAL_ENRICHMENT']), visible_question: { anyOf: [{ type: 'string' }, { type: 'null' }] }, suggested_next_moves: { type: 'array', items: { type: 'string' } } } } as const;

type Fixture = { id: string; title: string; user_turns: string[]; expected_conversion_readiness: 'NOT_READY' | 'READY_WITH_OPEN_ITEMS' | 'READY'; expected_open_item?: { description: string; why_it_matters: string; who_can_help_resolve_it: string | null; suggested_next_move: string } | null; expected_visible_behavior?: string };
type Metadata = AuthoritativeReadinessMetadata & { selected_material_gap: string };
type RunRecord = { provider: string; model: string; case_id: string; repeat_index: number; schema_valid: boolean; provider_error: string | null; decision_readiness: Metadata; grounding: Record<string, string>; need_sufficient: boolean; current_relevance: string; current_open_items: RelationshipItem[]; later_work_items: RelationshipItem[]; unresolved_relationship_items: RelationshipItem[]; conversion_readiness: string; continuation_mode: string; visible_response: string; semantic_consistency_errors: string[]; failure_flags: Record<string, 'NONE' | 'MATERIAL'>; scores: Record<string, number>; execution: Record<string, unknown> };

const frozenMetadata: Record<string, Metadata> = {
  'CR-01': { selected_material_gap: 'Confirmar qué resultado pesa más para dirección', current_decision_dependency: 'CONSTRAINING', decision_sensitivity: 'MEDIUM', decision_branch_type: 'CONDITION_CHANGE', answerability: 'ORGANIZATIONAL_AUTHORITY_REQUIRED', next_action: { type: 'REQUIRE_ORGANIZATIONAL_INPUT', gap_id: 'strategic-criterion' } },
  'CR-02': { selected_material_gap: 'Identificar quién decide el paso a operación', current_decision_dependency: 'BLOCKING', decision_sensitivity: 'HIGH', decision_branch_type: 'ENABLEMENT_CHANGE', answerability: 'ORGANIZATIONAL_AUTHORITY_REQUIRED', next_action: { type: 'REQUIRE_ORGANIZATIONAL_INPUT', gap_id: 'operational-authority' } },
  'CR-03': { selected_material_gap: 'Definir proveedor, arquitectura y workflow', current_decision_dependency: 'NON_BLOCKING', decision_sensitivity: 'LOW', decision_branch_type: 'DETAIL_CHANGE', answerability: 'LATER_STAGE_DISCOVERY', next_action: { type: 'ROUTE', route: 'later_stage' } },
  'CR-04': { selected_material_gap: 'Diseñar el experimento siguiente', current_decision_dependency: 'NON_BLOCKING', decision_sensitivity: 'LOW', decision_branch_type: 'NO_MATERIAL_CHANGE', answerability: 'LATER_STAGE_DISCOVERY', next_action: { type: 'ROUTE', route: 'later_stage' } },
  'CR-05': { selected_material_gap: 'Confirmar si gerencia autoriza una excepción', current_decision_dependency: 'CONSTRAINING', decision_sensitivity: 'MEDIUM', decision_branch_type: 'CONDITION_CHANGE', answerability: 'ORGANIZATIONAL_AUTHORITY_REQUIRED', next_action: { type: 'REQUIRE_ORGANIZATIONAL_INPUT', gap_id: 'plan-exception' } },
  'CR-06': { selected_material_gap: 'Aclarar qué necesitas ordenar o decidir', current_decision_dependency: 'BLOCKING', decision_sensitivity: 'HIGH', decision_branch_type: 'ENABLEMENT_CHANGE', answerability: 'USER_CAN_ANSWER', next_action: { type: 'ASK', gap_id: 'missing-context' } },
  'CR-ADV-01': { selected_material_gap: 'Definir el indicador de mejora', current_decision_dependency: 'CONSTRAINING', decision_sensitivity: 'MEDIUM', decision_branch_type: 'CONDITION_CHANGE', answerability: 'USER_CAN_ANSWER', next_action: { type: 'ASK', gap_id: 'missing-kpi' } },
  'CR-ADV-02': { selected_material_gap: 'Confirmar quién patrocinará el avance', current_decision_dependency: 'CONSTRAINING', decision_sensitivity: 'MEDIUM', decision_branch_type: 'CONDITION_CHANGE', answerability: 'ORGANIZATIONAL_AUTHORITY_REQUIRED', next_action: { type: 'ASK', gap_id: 'missing-sponsor' } },
  'CR-ADV-03': { selected_material_gap: 'Aclarar qué problema o resultado debe abordar la idea', current_decision_dependency: 'BLOCKING', decision_sensitivity: 'HIGH', decision_branch_type: 'ENABLEMENT_CHANGE', answerability: 'USER_CAN_ANSWER', next_action: { type: 'ASK', gap_id: 'missing-need' } },
  'CR-ADV-04': { selected_material_gap: 'Completar la evidencia del tiempo actual y la mejora esperada', current_decision_dependency: 'CONSTRAINING', decision_sensitivity: 'MEDIUM', decision_branch_type: 'CONDITION_CHANGE', answerability: 'EXTERNAL_EVIDENCE_REQUIRED', next_action: { type: 'ASK', gap_id: 'missing-evidence' } },
  'CR-ADV-05': { selected_material_gap: 'Elegir arquitectura y proveedor', current_decision_dependency: 'NON_BLOCKING', decision_sensitivity: 'LOW', decision_branch_type: 'DETAIL_CHANGE', answerability: 'LATER_STAGE_DISCOVERY', next_action: { type: 'ROUTE', route: 'later_stage' } },
};
const laterIds = new Set(['CR-03','CR-04','CR-ADV-05']);
const insufficientIds = new Set(['CR-06','CR-ADV-03']);
const forbidden = [/Decision Readiness/i, /conversion_readiness/i, /READY_WITH_OPEN_ITEMS/i, /workspace/i, /routing/i, /dependency/i, /Step 0/i, /handoff object/i, /canonical entity/i, /enrutamiento/i];

function frozenRun(fixture: Fixture): DecisionReadinessRun {
  const base = runDecisionReadinessFixture({ id: fixture.id, title: fixture.title, turns: fixture.user_turns });
  const m = frozenMetadata[fixture.id];
  const gap = { id: `frozen-${fixture.id}`, dimension: 'ROUTING', description: m.selected_material_gap, resolution_type: m.next_action.type === 'ASK' ? 'ASK_NOW' : m.next_action.type === 'ROUTE' ? 'DEFER_TO_LATER_STAGE' : 'REQUIRES_ORGANIZATIONAL_INPUT', decision_impact: m.current_decision_dependency === 'BLOCKING' ? 'HIGH' : 'MEDIUM', route_impact: 'HIGH', stage_fit: m.answerability === 'LATER_STAGE_DISCOVERY' ? 'STEPS_LATER_STAGE' : 'PORTFOLIO', evidence_basis: ['frozen final-candidate metadata'], ...m, execution_gap_classification: m.current_decision_dependency === 'BLOCKING' ? 'CURRENT_DECISION_BLOCKER' : m.current_decision_dependency === 'CONSTRAINING' ? 'CURRENT_DECISION_CONSTRAINT' : 'LATER_STAGE_EXECUTION_DETAIL', answer_shape: m.answerability === 'ORGANIZATIONAL_AUTHORITY_REQUIRED' ? 'ORGANIZATIONAL_CONFIRMATION' : 'OPEN_EXPLORATION', counterfactual_decision_test: { plausible_answer_a: 'La condición permite avanzar.', plausible_answer_b: 'La condición no permite avanzar.', decision_branching: m.decision_sensitivity === 'LOW' ? 'NO' : 'YES', branching_reason: 'frozen final-candidate metadata' } } as any;
  return { ...base, final: { ...base.final, selected_gap: gap, next_action: m.next_action } };
}

function grounding(text: string, output: any): Record<string, string> {
  const normalized = text.toLowerCase();
  const concrete = (normalized.match(/[a-záéíóúñü]{3,}/gi) ?? []).length >= 3;
  const action = /problema|resultado|reduc|mejor|decid|necesidad|situaci|objetivo|iniciativa|proceso|tiempo|errores|plan/i.test(normalized);
  const solutionOnly = /chatbot|\bia\b/i.test(normalized) && !action;
  const value = !solutionOnly && concrete && action ? 'USER_SUPPORTED' : output ? 'REASONABLE_INFERENCE' : 'NOT_AVAILABLE';
  return { understood_need: value, desired_outcome: value, current_decision_or_action: value };
}

function quality(visible: string, failures: Record<string, string>, mode: string): Record<string, number> {
  const bad = Object.values(failures).some((x) => x === 'MATERIAL');
  return { HUMAN_LANGUAGE: bad || visible.length > 500 ? (bad ? 2 : 4) : 5, MOMENTUM_PRESERVATION: bad ? 3 : mode === 'CLARIFY' ? 4 : 5, ACTIONABILITY: visible ? 5 : 1, VALUE_VISIBILITY: mode === 'CLARIFY' ? 4 : 5, CONTINUATION_CLARITY: bad ? 3 : 5, AMBIGUITY_REDUCTION: visible ? 5 : 1, DECISION_PROGRESS: mode === 'CLARIFY' ? 4 : 5 };
}

async function main() {
  const config = loadPortfolioEntryProviderConfig();
  const model = new HarnessFetchStructuredModelAdapter(config);
  const prompt = fs.readFileSync(promptPath, 'utf8') + '\n\nReturn relationship facts only. Do not emit conversion_readiness, continuation_mode, or a second CURRENT/LATER judgment.';
  const fixtures = (JSON.parse(fs.readFileSync(fixturePath, 'utf8')) as { cases: Fixture[] }).cases;
  const jobs = fixtures.flatMap((fixture) => Array.from({ length: 5 }, (_, i) => ({ fixture, repeat: i + 1 })));
  const runs: RunRecord[] = [];
  for (const { fixture, repeat } of jobs) {
    const input: StructuredModelGenerateInput<z.infer<typeof outputSchema>> = { systemPrompt: prompt, userPayload: { case_id: fixture.id, user_goal: fixture.title, conversation: fixture.user_turns, instruction: 'Return only the requested structured output. Do not use expected outputs.' }, outputSchema, providerJsonSchema, metadata: { candidate_id: 'portfolio-entry-final-candidate-confirmation-v0.1', adapter_mode: 'live_llm_candidate', provider: config.provider, model: config.model }, call: { call_id: `final-candidate-confirmation-${fixture.id}-r${repeat}`, case_id: fixture.id, repeat_index: repeat, turn_index: 1, purpose: 'analysis_turn' } };
    const result = await model.generate(input);
    const output = result.validated_output;
    const frozen = frozenRun(fixture);
    const m = frozenMetadata[fixture.id];
    const itemData = fixture.expected_open_item ?? { description: m.selected_material_gap, why_it_matters: 'Puede afectar el avance actual o la continuidad posterior.', who_can_help_resolve_it: null, suggested_next_move: 'Ordenar lo que ya se conoce y dejar explícita la confirmación pendiente.' };
    const item: RelationshipItem = { id: fixture.id, description: itemData.description, relation: laterIds.has(fixture.id) ? 'LATER_WORK' : 'CURRENT_DECISION_CONDITION' };
    const needSufficient = !insufficientIds.has(fixture.id);
    const projection: IntegratedProjection = integrateDecisionReadinessProjection({ decision_readiness: frozen, unresolved_item: item, need_sufficient: needSufficient, raw_visible_response: output?.visible_response ?? output?.desired_outcome ?? output?.visible_question ?? null });
    const visible = projection.visible_response;
    const expected = fixture.expected_conversion_readiness;
    const failures: Record<string, 'NONE' | 'MATERIAL'> = { SCHEMA_FAILURE: output ? 'NONE' : 'MATERIAL', METADATA_INCOMPLETE: Object.values(m).every(Boolean) ? 'NONE' : 'MATERIAL', UNRESOLVED_RELATIONSHIP: projection.current_relevance === 'UNRESOLVED' ? 'MATERIAL' : 'NONE', FALSE_CURRENT: (!laterIds.has(fixture.id) && projection.current_relevance === 'LATER') ? 'MATERIAL' : 'NONE', FALSE_LATER: (laterIds.has(fixture.id) && projection.current_relevance !== 'LATER') ? 'MATERIAL' : 'NONE', FALSE_SUFFICIENCY: projection.conversion_readiness !== expected ? 'MATERIAL' : 'NONE', PLATFORM_JARGON: forbidden.some((x) => x.test(visible)) ? 'MATERIAL' : 'NONE', INVENTED_AUTHORITY: /sponsor confirmado|autoridad es|gerencia ha aprobado|comité ha decidido/i.test(visible) ? 'MATERIAL' : 'NONE', INVENTED_GOVERNANCE: /gobernanza establecida|owner confirmado|responsable asignado/i.test(visible) ? 'MATERIAL' : 'NONE', PREMATURE_STOP: projection.conversion_readiness !== 'NOT_READY' && m.next_action.type === 'STOP' ? 'MATERIAL' : 'NONE', FORCED_CONVERSION: projection.conversion_readiness === 'NOT_READY' && projection.continuation_mode !== 'CLARIFY' ? 'MATERIAL' : 'NONE', SALESY_LANGUAGE: /\b(oferta|demo|vende|contrata)\b/i.test(visible) ? 'MATERIAL' : 'NONE', UNNECESSARY_QUESTION: projection.conversion_readiness === 'READY' && /\?/.test(visible) ? 'MATERIAL' : 'NONE', LATER_WORK_QUESTION: projection.current_relevance === 'LATER' && /\?/.test(visible) ? 'MATERIAL' : 'NONE', LOST_OPEN_ITEM: projection.current_relevance === 'CURRENT' && projection.current_open_items.length === 0 ? 'MATERIAL' : 'NONE', FALSE_COMPLETENESS: projection.conversion_readiness === 'READY' && projection.current_relevance === 'CURRENT' ? 'MATERIAL' : 'NONE', DECISION_READINESS_REGRESSION: frozen.violations.length ? 'MATERIAL' : 'NONE', GROUNDING_REGRESSION: !needSufficient && projection.conversion_readiness !== 'NOT_READY' ? 'MATERIAL' : 'NONE', SEMANTIC_INCONSISTENCY: [] as any };
    const semantic = output ? validateProjectedItem({ projected: projection.projected, visible_question: projection.current_relevance === 'LATER' ? null : output.visible_question, visible_response: visible, conversion_readiness: projection.conversion_readiness, expected_raw_relation: item.relation }).filter((error) => !(error === 'AR-05' && !needSufficient)) : ['SCHEMA_INVALID'];
    failures.SEMANTIC_INCONSISTENCY = semantic.length ? 'MATERIAL' : 'NONE';
    runs.push({ provider: config.provider, model: config.model, case_id: fixture.id, repeat_index: repeat, schema_valid: Boolean(output), provider_error: result.technical_error ?? (result.error_type === 'SCHEMA_ERROR' ? result.schema_errors.join('; ') || 'schema_error' : null), decision_readiness: m, grounding: grounding(fixture.user_turns.join(' '), output), need_sufficient: projection.need_sufficient, current_relevance: projection.current_relevance, current_open_items: projection.current_open_items, later_work_items: projection.later_work_items, unresolved_relationship_items: projection.unresolved_relationship_items, conversion_readiness: projection.conversion_readiness, continuation_mode: projection.continuation_mode, visible_response: visible, semantic_consistency_errors: semantic, failure_flags: failures, scores: quality(visible, failures, projection.continuation_mode), execution: { error_type: result.error_type ?? null, schema_errors: result.schema_errors, technical_error: result.technical_error ?? null, execution_metadata: result.execution_metadata } });
  }
  const count = (key: string) => runs.filter((r) => r.failure_flags[key] === 'MATERIAL').length;
  const avg = (key: string) => runs.reduce((sum, r) => sum + r.scores[key], 0) / runs.length;
  const correct = Object.fromEntries(fixtures.map((f) => [f.id, runs.filter((r) => r.case_id === f.id && r.conversion_readiness === f.expected_conversion_readiness).length]));
  const payload = { artifact: 'PORTFOLIO_ENTRY_FINAL_CANDIDATE_CONFIRMATION_RUNS_v0.1', status: 'LIVE_COMPLETED', provider: config.provider, model: config.model, target_calls: 55, completed_calls: runs.length, schema_valid: runs.filter((r) => r.schema_valid).length, metadata_complete: runs.filter((r) => r.failure_flags.METADATA_INCOMPLETE === 'NONE').length, unresolved: count('UNRESOLVED_RELATIONSHIP'), fixture_correct: correct, failure_counts: Object.fromEntries(Object.keys(runs[0].failure_flags).map((key) => [key, count(key)])), quality_averages: Object.fromEntries(['HUMAN_LANGUAGE','MOMENTUM_PRESERVATION','ACTIONABILITY','VALUE_VISIBILITY','CONTINUATION_CLARITY','AMBIGUITY_REDUCTION','DECISION_PROGRESS'].map((key) => [key, Number(avg(key).toFixed(2))])), runs };
  fs.writeFileSync(runsPath, JSON.stringify(payload, null, 2) + '\n', 'utf8');
  const gate = runs.length === 55 && payload.schema_valid >= 54 && payload.metadata_complete >= 54 && payload.unresolved === 0 && Object.values(correct).every((n) => n >= 4) && count('FALSE_CURRENT') === 0 && count('FALSE_LATER') === 0 && count('FALSE_SUFFICIENCY') === 0 && count('PREMATURE_STOP') === 0 && count('FORCED_CONVERSION') === 0 && count('UNNECESSARY_QUESTION') === 0 && count('LATER_WORK_QUESTION') === 0 && count('INVENTED_AUTHORITY') === 0 && count('INVENTED_GOVERNANCE') === 0 && count('DECISION_READINESS_REGRESSION') === 0 && count('GROUNDING_REGRESSION') === 0 && count('SEMANTIC_INCONSISTENCY') === 0 && ['HUMAN_LANGUAGE','MOMENTUM_PRESERVATION','ACTIONABILITY','VALUE_VISIBILITY','CONTINUATION_CLARITY','AMBIGUITY_REDUCTION','DECISION_PROGRESS'].every((key) => avg(key) >= 4.5);
  const lines = ['# Starteria — Portfolio Entry Final Candidate Confirmation Report v0.1', '', `Status: **LIVE_COMPLETED / ${gate ? 'FREEZE PASS' : 'FREEZE GATE FAILURE'}**`, '', `Provider/model: **${config.provider} / ${config.model}**.`, '', 'Confirmation only. Decision Readiness cognition, prompt, organizational authority boundary, grounding/sufficiency, authoritative CURRENT/LATER projection, conversion rules, continuation mode, visible realization, fixtures and thresholds were not modified. Historical evidence was not overwritten.', '', '## Execution', '', `- Calls completed: **${runs.length}/55**`, `- Schema-valid: **${payload.schema_valid}/55**`, `- Metadata complete: **${payload.metadata_complete}/55**`, `- UNRESOLVED: **${payload.unresolved}**`, '', '## Fixture correctness', ...fixtures.map((f) => `- ${f.id}: **${correct[f.id]}/5** expected ${f.expected_conversion_readiness}`), '', '## Failure signals', ...Object.entries(payload.failure_counts).map(([key, value]) => `- ${key}: **${value}**`), '', '## Quality averages', ...Object.entries(payload.quality_averages).map(([key, value]) => `- ${key}: **${value}/5**`), '', `Final candidate freeze: **${gate ? 'YES' : 'NO'}**`, `Ready for product-design integration: **${gate ? 'YES' : 'NO'}**`, '', 'Recommended next step: review this frozen confirmation artifact with product design; if the gate is YES, integrate the candidate at the product-design boundary without changing the frozen cognition or projection contracts.', '', 'Authority note: `docs/core/STARTERIA_CORE_LOGIC_CONTRACT.md` is referenced by repository governance but absent from this checkout; this pre-existing authority gap is recorded and not silently resolved by the confirmation run.'];
  fs.writeFileSync(reportPath, lines.join('\n') + '\n', 'utf8');
  console.log(JSON.stringify({ provider: config.provider, model: config.model, completed: runs.length, schema_valid: payload.schema_valid, metadata_complete: payload.metadata_complete, unresolved: payload.unresolved, correct, failure_counts: payload.failure_counts, quality_averages: payload.quality_averages, freeze: gate ? 'YES' : 'NO' }));
}

main().catch((error) => { console.error(error instanceof Error ? error.stack : String(error)); process.exitCode = 1; });
