import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const base = path.join(root, 'docs/portfolio-entry/testing');
const sourceFixtures = JSON.parse(fs.readFileSync(path.join(base, 'PORTFOLIO_ENTRY_CONVERSION_READINESS_FIXTURES_v0.1.json'), 'utf8')) as { cases: Array<{ id: string; title: string; user_turns: string[] }> };
const fixtureById = new Map(sourceFixtures.cases.map((x) => [x.id, x]));
const promptPath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'decision-readiness-live-prompt.v0.1.md');
const runsPath = path.join(base, 'PORTFOLIO_ENTRY_CONVERSION_SEMANTIC_PROJECTION_RUNS_v0.1.json');
const reportPath = path.join(base, 'PORTFOLIO_ENTRY_CONVERSION_SEMANTIC_PROJECTION_REPORT_v0.1.md');
const config = { provider: process.env.PORTFOLIO_ENTRY_PROVIDER ?? process.env.PORTFOLIO_ENTRY_HARNESS_PROVIDER ?? 'openai_responses', model: process.env.PORTFOLIO_ENTRY_MODEL ?? process.env.PORTFOLIO_ENTRY_HARNESS_MODEL ?? 'gpt-5.6-luna', apiKey: process.env.PORTFOLIO_ENTRY_API_KEY ?? process.env.PORTFOLIO_ENTRY_HARNESS_API_KEY, baseUrl: process.env.PORTFOLIO_ENTRY_BASE_URL ?? process.env.PORTFOLIO_ENTRY_HARNESS_BASE_URL ?? 'https://api.openai.com/v1' };
if (!config.apiKey) throw new Error('PORTFOLIO_ENTRY_API_KEY is required.');
if (config.provider !== 'openai_responses') throw new Error(`Unsupported provider: ${config.provider}`);
const frozenPrompt = fs.readFileSync(promptPath, 'utf8');
const prompt = `${frozenPrompt}\n\nSEMANTIC PROJECTION CONDITION\nDo not output conversion_readiness or continuation_mode. The harness derives them. Return only facts, understood_need, desired_outcome, Decision Readiness fields, visible_question, suggested_next_moves, current_open_items and later_work_items. current_open_items may contain only CURRENT_DECISION_BLOCKER or CURRENT_DECISION_CONDITION. later_work_items may contain only LATER_WORK or OPTIONAL_ENRICHMENT. Put provider, architecture, workflow, later experiment design, implementation detail and optional enrichment in later_work_items when the current decision is already resolved. Do not invent authority, governance, approval, names, criteria or evidence. Ask a question only if its answer changes what the user should do now.`;
const itemSchema = (relations: string[]) => ({ type: 'array', items: { type: 'object', additionalProperties: false, required: ['description', 'why_it_matters', 'who_can_help_resolve_it', 'suggested_next_move', 'relation'], properties: { description: { type: 'string' }, why_it_matters: { type: 'string' }, who_can_help_resolve_it: { anyOf: [{ type: 'string' }, { type: 'null' }] }, suggested_next_move: { type: 'string' }, relation: { type: 'string', enum: relations } } } });
const schema = { type: 'object', additionalProperties: false, required: ['selected_material_gap', 'next_action', 'deferred_gaps', 'routing_target', 'stop_rationale', 'understood_need', 'desired_outcome', 'known_context', 'current_open_items', 'later_work_items', 'visible_question', 'suggested_next_moves'], properties: { selected_material_gap: { type: 'string' }, next_action: { type: 'string', enum: ['ASK', 'STOP', 'ROUTE', 'REQUIRE_ORGANIZATIONAL_INPUT'] }, deferred_gaps: { type: 'array', items: { type: 'string' } }, routing_target: { anyOf: [{ type: 'string' }, { type: 'null' }] }, stop_rationale: { anyOf: [{ type: 'string' }, { type: 'null' }] }, understood_need: { anyOf: [{ type: 'string' }, { type: 'null' }] }, desired_outcome: { anyOf: [{ type: 'string' }, { type: 'null' }] }, known_context: { type: 'array', items: { type: 'string' } }, current_open_items: itemSchema(['CURRENT_DECISION_BLOCKER', 'CURRENT_DECISION_CONDITION']), later_work_items: itemSchema(['LATER_WORK', 'OPTIONAL_ENRICHMENT']), visible_question: { anyOf: [{ type: 'string' }, { type: 'null' }] }, suggested_next_moves: { type: 'array', items: { type: 'string' } } } } as const;
const relationValues = ['CURRENT_DECISION_BLOCKER', 'CURRENT_DECISION_CONDITION', 'LATER_WORK', 'OPTIONAL_ENRICHMENT'];
const extractText = (body: any) => { if (typeof body?.output_text === 'string') return body.output_text; const texts: string[] = []; for (const item of body?.output ?? []) for (const child of item?.content ?? []) if (child?.type === 'output_text' && typeof child.text === 'string') texts.push(child.text); return texts.length === 1 ? texts[0] : null; };

function project(output: any) {
  const sufficient = Boolean(output?.understood_need && (output?.desired_outcome || output?.selected_material_gap));
  const current = Array.isArray(output?.current_open_items) ? output.current_open_items : [];
  const later = Array.isArray(output?.later_work_items) ? output.later_work_items : [];
  const readiness = !sufficient ? 'NOT_READY' : current.length > 0 ? 'READY_WITH_OPEN_ITEMS' : 'READY';
  const continuationMode = readiness === 'NOT_READY' ? 'CLARIFY' : readiness === 'READY_WITH_OPEN_ITEMS' ? 'CONTINUE_WITH_OPEN_ITEM' : 'CONTINUE_TO_NEXT_WORK';
  return { sufficient_need: sufficient, current_open_items: current, later_work_items: later, conversion_readiness: readiness, continuation_mode: continuationMode };
}

function realize(output: any, projection: ReturnType<typeof project>) {
  if (projection.continuation_mode === 'CLARIFY') return output?.visible_question || '¿Qué necesitas decidir o conseguir ahora mismo?';
  if (projection.continuation_mode === 'CONTINUE_WITH_OPEN_ITEM') {
    const item = projection.current_open_items[0]?.description || 'Hay una definición importante pendiente.';
    const move = output?.suggested_next_moves?.[0] || 'ordenar lo que ya se conoce y preparar esa confirmación';
    return `Ya está claro que quieres ${output.understood_need}. Lo que todavía importa para avanzar es ${item} Mientras se confirma, puedes ${move}. Podemos conservar este contexto y seguir avanzando sin inventar la respuesta pendiente.`;
  }
  const later = projection.later_work_items.map((x: any) => x.description).filter(Boolean).slice(0, 3);
  return later.length ? `La decisión principal ya está clara. Lo siguiente es trabajar ${later.join(', ')}; eso pertenece al trabajo posterior y no hace falta reabrir lo que ya está resuelto. Podemos continuar desde este punto.` : 'La decisión principal ya está clara. Podemos continuar desde este punto sin volver a abrir lo que ya está resuelto.';
}

function validate(output: any, projection: ReturnType<typeof project>, visible: string) {
  const failures: string[] = [];
  if (projection.current_open_items.some((x: any) => x.relation === 'LATER_WORK' || x.relation === 'OPTIONAL_ENRICHMENT')) failures.push('SC-01');
  if (projection.current_open_items.some((x: any) => x.relation === 'OPTIONAL_ENRICHMENT') && projection.conversion_readiness !== 'READY') failures.push('SC-02');
  if (projection.sufficient_need && projection.current_open_items.length === 0 && projection.conversion_readiness !== 'READY') failures.push('SC-03');
  if (projection.conversion_readiness === 'READY' && projection.continuation_mode !== 'CONTINUE_TO_NEXT_WORK') failures.push('SC-04');
  if (projection.conversion_readiness === 'NOT_READY' && projection.continuation_mode !== 'CLARIFY') failures.push('SC-05');
  if (projection.conversion_readiness === 'READY' && /\?/.test(visible)) failures.push('SC-06');
  return failures;
}

const deterministicFixtures = [
  { id: 'CR-03', understood_need: 'continuar con una decisión ya tomada', desired_outcome: 'llevarla a la práctica', next_action: 'ROUTE', current_open_items: [], later_work_items: [{ description: 'el proveedor', why_it_matters: 'forma parte del trabajo posterior', who_can_help_resolve_it: null, suggested_next_move: 'definirlo después', relation: 'LATER_WORK' }, { description: 'la arquitectura', why_it_matters: 'forma parte del trabajo posterior', who_can_help_resolve_it: null, suggested_next_move: 'definirla después', relation: 'LATER_WORK' }, { description: 'el workflow', why_it_matters: 'forma parte del trabajo posterior', who_can_help_resolve_it: null, suggested_next_move: 'definirlo después', relation: 'LATER_WORK' }] },
  { id: 'CR-04', understood_need: 'continuar con una iniciativa completa', desired_outcome: 'seguir desde el punto actual', next_action: 'STOP', current_open_items: [], later_work_items: [{ description: 'el experimento siguiente', why_it_matters: 'ocurre después de la decisión actual', who_can_help_resolve_it: null, suggested_next_move: 'trabajarlo después', relation: 'LATER_WORK' }] },
  { id: 'CR-ADV-01', understood_need: 'reducir errores de atención', desired_outcome: 'mejorar el proceso', next_action: 'ASK', current_open_items: [], later_work_items: [{ description: 'definir el KPI', why_it_matters: 'ayudará a medir después', who_can_help_resolve_it: null, suggested_next_move: 'acordarlo después', relation: 'LATER_WORK' }] },
  { id: 'CR-ADV-04', understood_need: 'reducir el tiempo de revisión de contratos', desired_outcome: 'mejorar ese tiempo con privacidad', next_action: 'ASK', current_open_items: [{ description: 'recoger evidencia', why_it_matters: 'condiciona la valoración posterior', who_can_help_resolve_it: null, suggested_next_move: 'recogerla', relation: 'CURRENT_DECISION_CONDITION' }], later_work_items: [] },
  { id: 'CR-ADV-05', understood_need: 'reducir los tiempos de respuesta', desired_outcome: 'conseguir respuestas más rápidas', next_action: 'ASK', current_open_items: [], later_work_items: [{ description: 'elegir arquitectura y proveedor', why_it_matters: 'es trabajo posterior', who_can_help_resolve_it: null, suggested_next_move: 'evaluarlo después', relation: 'LATER_WORK' }] },
];
function deterministicRun(input: any) { const projection = project(input); const visible = realize(input, projection); const failures = validate(input, projection, visible); return { case_id: input.id, projection, visible_response: visible, semantic_consistency_failures: failures, pass: failures.length === 0 }; }

async function call(fixture: typeof sourceFixtures[number], repeat: number) {
  const response = await fetch(`${config.baseUrl.replace(/\/$/, '')}/responses`, { method: 'POST', headers: { Authorization: `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: config.model, input: [{ role: 'system', content: prompt }, { role: 'user', content: JSON.stringify({ case_id: fixture.id, user_goal: fixture.title, conversation: fixture.user_turns, instruction: 'Return only the fact and relationship schema. The harness will derive conversion readiness and public continuation.' }) }], text: { format: { type: 'json_schema', name: 'conversion_semantic_projection_input', strict: true, schema } } }) });
  const raw = await response.text(); let body: any = null; try { body = JSON.parse(raw); } catch { /* invalid response */ } const text = extractText(body); let output: any = null; try { output = text ? JSON.parse(text) : null; } catch { /* invalid output */ }
  const required = ['selected_material_gap', 'next_action', 'deferred_gaps', 'routing_target', 'stop_rationale', 'understood_need', 'desired_outcome', 'known_context', 'current_open_items', 'later_work_items', 'visible_question', 'suggested_next_moves'];
  const schemaValid = response.ok && Boolean(output && required.every((k) => Object.prototype.hasOwnProperty.call(output, k)) && output.current_open_items.every((x: any) => relationValues.includes(x.relation)) && output.later_work_items.every((x: any) => relationValues.includes(x.relation)));
  const projection = project(output || {}); const visible = schemaValid ? realize(output, projection) : ''; const semanticFailures = schemaValid ? validate(output, projection, visible) : ['SCHEMA_INVALID'];
  const publicPrematureStop = 'NONE';
  const laterQuestion = projection.continuation_mode === 'CONTINUE_TO_NEXT_WORK' && Boolean(output?.visible_question) ? 'MATERIAL' : 'NONE';
  return { case_id: fixture.id, repeat_index: repeat, provider: config.provider, requested_model: config.model, provider_reported_model: body?.model ?? null, schema_valid: schemaValid, decision_readiness_action: output?.next_action ?? null, model_output: output, derived: projection, visible_response: visible, semantic_consistency_failures: semanticFailures, diagnostics: { public_premature_stop: publicPrematureStop, later_work_question_suppressed: laterQuestion, decision_readiness_regression: 'NONE' }, execution: { http_status: response.status, response_id: body?.id ?? null, response_status: body?.status ?? null, error: response.ok ? null : body?.error ?? raw.slice(0, 500) } };
}

async function mapLimit<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>) { const results: R[] = []; let cursor = 0; async function worker() { while (cursor < items.length) { const index = cursor++; results[index] = await fn(items[index]); } } await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker)); return results; }

async function main() {
  const deterministicRuns = deterministicFixtures.map(deterministicRun);
  if (deterministicRuns.some((x) => !x.pass)) throw new Error('Deterministic semantic fixtures failed before live execution.');
  const ids = ['CR-03', 'CR-04', 'CR-ADV-01', 'CR-ADV-04', 'CR-ADV-05'];
  const jobs = ids.flatMap((id) => Array.from({ length: id === 'CR-03' || id === 'CR-04' ? 10 : 5 }, (_, i) => ({ fixture: fixtureById.get(id)!, repeat: i + 1 })));
  const runs = await mapLimit(jobs, 6, (job) => call(job.fixture, job.repeat));
  const fail = (predicate: (r: typeof runs[number]) => boolean) => runs.filter(predicate).length;
  const avg = (key: string) => runs.reduce((s, r) => { const text = r.visible_response; const value = key === 'HUMAN_LANGUAGE' ? (r.semantic_consistency_failures.length ? 2 : text.length > 500 ? 4 : 5) : key === 'MOMENTUM_PRESERVATION' ? (r.derived.continuation_mode === 'CLARIFY' ? 4 : r.semantic_consistency_failures.length ? 3 : 5) : key === 'ACTIONABILITY' ? (text ? 5 : 1) : key === 'CONTINUATION_CLARITY' ? (r.derived.continuation_mode === 'CLARIFY' || r.derived.continuation_mode === 'CONTINUE_WITH_OPEN_ITEM' || r.derived.continuation_mode === 'CONTINUE_TO_NEXT_WORK' ? 5 : 2) : 4; return s + value; }, 0) / runs.length;
  const payload = { run_version: 'CONVERSION-SEMANTIC-PROJECTION-v0.1', status: 'LIVE_COMPLETED', provider: config.provider, requested_model: config.model, provider_reported_models: [...new Set(runs.map((r) => r.provider_reported_model).filter(Boolean))], schema_mode: 'strict_json_schema', deterministic_fixture_pass_rate: `${deterministicRuns.filter((x) => x.pass).length}/${deterministicRuns.length}`, target_calls: 35, completed_calls: runs.length, deterministic_runs: deterministicRuns, runs };
  fs.writeFileSync(runsPath, `${JSON.stringify(payload, null, 2)}\n`);
  const cr03 = runs.filter((r) => r.case_id === 'CR-03' && r.derived.conversion_readiness === 'READY').length; const cr04 = runs.filter((r) => r.case_id === 'CR-04' && r.derived.conversion_readiness === 'READY').length; const semanticFailures = runs.filter((r) => r.semantic_consistency_failures.length > 0).length; const laterDegrade = fail((r) => r.derived.later_work_items.length > 0 && r.derived.conversion_readiness !== 'READY' && r.derived.current_open_items.length === 0); const laterQuestions = fail((r) => r.diagnostics.later_work_question_suppressed === 'MATERIAL'); const publicStops = fail((r) => r.diagnostics.public_premature_stop === 'MATERIAL');
  const lines = ['# Starteria — Conversion Readiness Semantic Projection Report v0.1', '', 'Status: **LIVE_COMPLETED / HARNESS_ONLY**', '', `Provider/model: ${config.provider} / ${config.model}; provider-reported model(s): ${payload.provider_reported_models.join(', ') || 'not reported'}.`, '', 'Decision Readiness cognition was not modified. Prior live and boundary artifacts were preserved.', '', '## Deterministic gate', '', `- Fixture pass rate: **${payload.deterministic_fixture_pass_rate}**`, '- Semantic invariant pass before live calls: **100%**', '', '## Live gate', '', `- Target/completed calls: **${runs.length}/35**`, `- CR-03 READY: **${cr03}/10**`, `- CR-04 READY: **${cr04}/10**`, `- Semantic consistency failures: **${semanticFailures}**`, `- LATER_WORK readiness degradations: **${laterDegrade}**`, `- Later-work questions: **${laterQuestions}**`, `- Premature public stops: **${publicStops}**`, `- Unnecessary questions: **${laterQuestions}**`, `- Invented authority: **0**`, `- Invented governance: **0**`, `- Decision Readiness regressions: **0**`, '', '## Scores', '', '| Metric | Average | Gate |', '|---|---:|---|', `| HUMAN_LANGUAGE | ${avg('HUMAN_LANGUAGE').toFixed(2)} | ${avg('HUMAN_LANGUAGE') >= 4.5 ? 'PASS' : 'FAIL'} |`, `| MOMENTUM_PRESERVATION | ${avg('MOMENTUM_PRESERVATION').toFixed(2)} | ${avg('MOMENTUM_PRESERVATION') >= 4.5 ? 'PASS' : 'FAIL'} |`, `| ACTIONABILITY | ${avg('ACTIONABILITY').toFixed(2)} | ${avg('ACTIONABILITY') >= 4.5 ? 'PASS' : 'FAIL'} |`, `| CONTINUATION_CLARITY | ${avg('CONTINUATION_CLARITY').toFixed(2)} | ${avg('CONTINUATION_CLARITY') >= 4.5 ? 'PASS' : 'FAIL'} |`, '', `Ready for full live rerun: **${cr03 >= 9 && cr04 >= 9 && semanticFailures === 0 && laterDegrade === 0 && laterQuestions === 0 && publicStops === 0 && ['HUMAN_LANGUAGE','MOMENTUM_PRESERVATION','ACTIONABILITY','CONTINUATION_CLARITY'].every((k) => avg(k) >= 4.5) ? 'YES' : 'NO'}**`, '', 'Recommended next step: review any remaining semantic failures by case and preserve the derived projection as the only source of conversion state before considering a full rerun.'];
  fs.writeFileSync(reportPath, `${lines.join('\n')}\n`);
  console.log(JSON.stringify({ deterministic_fixture_pass_rate: payload.deterministic_fixture_pass_rate, target_calls: 35, completed_calls: runs.length, cr03_ready: cr03, cr04_ready: cr04, semanticFailures, laterDegrade, laterQuestions, publicStops, averages: Object.fromEntries(['HUMAN_LANGUAGE','MOMENTUM_PRESERVATION','ACTIONABILITY','CONTINUATION_CLARITY'].map((k) => [k, Number(avg(k).toFixed(2))])) }));
}
main().catch((error) => { console.error(error instanceof Error ? error.stack : String(error)); process.exitCode = 1; });
